---
_hotel_id: THE618
_portal_id: required-but-empty
latitude: 40.73247
longitude: -73.99692
name: The Marlton Hotel
email: ''
phone_number: "--"
address:
  street1: 5 W 8th St
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10011'
